### ISSUE TITLE
Architettura ed integrazione SIGLA

### ISSUE THREAD

**Issue by kratosmat** [consiglionazionaledellericerche/sigla-ng#25]
Salve,
al fine di valutare gli importanti lavori di aggiornamento effettuati sul progetto sigla-ng mi premeva comprendere appieno la relazione che c'è con il sistema main.
In particolare mi chiedevo quali fossero i punti di integrazione fra sigla-ng ed sigla-main, se si condividesse solo il DB o ng usasse anche servizi e interfacce esposte da main. Non trovando documenti faccio qui la domanda.

Grazie,
Matteo.

**Comment by mspasiano** [comment]
Ciao, il progetto condivide il DB con sigla-main basato su Wildfly/Thorntail, l'interfaccia è basta su Angular 12 mentre il backend è su Spring Boot, utilizza servizi REST esposti da sigla-main soprattuto con risposta text/html.
Siccome il progetto è in produzione da circa 20 anni, l'idea è quella di migrare le funzionalità verso sigla-ng o al massimo creare sulla parte sigla-main servizi REST con risposta json.
Spero di aver chiarito i tuoi dubbi in merito.

**Comment by kratosmat** [comment]
Ciao Marco,
grazie innanzitutto della celere risposta.
Mi hai chiarito sicuramente la situazione ma ho ancora qualche dubbio e approfitto della tua disponibilità: 
- sigla-main è comunque basato su Thorntail, una tecnologia ormai non più supportata dalla community, è vostra intenzione sostituirla con wildfly puro?
- i servizi REST ad oggi esposti da main ed usati da ng sono richiamati M2M o direttamente da Angular? Nel secondo caso, come viene gestita l'autenticazione?
Infine, l'architettura mi sembra molto modulare e credo che un passaggio a spring-boot sia fattibile senza riscrivere tanta percentuale di codice.

Saluti,
Matteo.

**Comment by mspasiano** [comment]
- Si l'idea è di passare a https://docs.wildfly.org/bootablejar/ stavamo valutando anche Quarkus ma l'intervento sarebbe molto oneroso, comunque attualmente puoi anche deployarlo su wildfly senza thorntail che invece è molto comodo in fase di sviluppo e debug.
- I servizi vengono richiamati M2M attualmente facendo una doppia autenticazione, che stiamo per togliere con il passaggio ad SSO con Keycloak
- Il problema rincipale è che andrebbero rifatte tutte le maschere e ti assicuro che sono tante, per cui se l'ente decide di investire o abbiamo un contributo forte dalla community la cosa si potrebbe fare magari a step successivi, ora siamo prettamente concentrati sul passaggio all'economico patrimoniale e cogliamo l'occassione per eliminare tutto il codice PLSQL per renderlo compliant con Postgres e altri RDBMS

Ciao

**Comment by kratosmat** [comment]
Ciao Marco,
quando si parla di servizi REST text/html si intende che l'applicazione ng richiama delle pagine html di main e le visualizza con componenti tipo iframe?

Grazie ancora,
Matteo.

**Comment by mspasiano** [comment]
No l'html sanificato viene aggiunto qui:

https://github.com/consiglionazionaledellericerche/sigla-ng/blob/fd17a09c658c0f7670609ad7d7d9a777a966faf1/src/main/webapp/app/workspace/workspace.component.html#L28

Attraverso questo metodo:

https://github.com/consiglionazionaledellericerche/sigla-ng/blob/fd17a09c658c0f7670609ad7d7d9a777a966faf1/src/main/webapp/app/workspace/workspace.component.ts#L209-L276
